### ISSUE TITLE
もっといいリポジトリー名があるかも知れません

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#1]
@fumieval 
まだ何もできていないのにすみません、
今日の口頭での議論だと、Haskell-jpコミュニティーで行っていること、行ったこと、行うべきことをまとめたり、発生した問題についてIssueで議論するためのリポジトリーだという認識です。
なので単純に「haskell-jp/community」という名前でどうかな、と思っています。
もっといい名前があるかも知れませんが、取り急ぎ一案として。

**Comment by fumieval** [comment]
了解です。変更しました
