### ISSUE TITLE
招待講演？

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#10]

**Comment by igrep** [comment]
@ekmett 氏と当日どう落ち合うかをそろそろ検討せねば。直接来るつもりなんだろうか。
Now we should consider how to meet with @ekmett at the day. Is he going to the venue directly without any guide by us?

**Comment by ekmett** [comment]
I could probably figure it out, but I could probably use some assistance getting to the venue, or at least someone letting me know generally where it is a day or two in advance if not. My ability to navigate using my terribly limited japanese hasn't been tested in 20 years.

My flight is booked and I plan on booking my hotel when I get back from my next side-trip. At that point I should have a better idea for how to get around and how far away I'll be. For that matter, I'm definitely open to hotel suggestions if folks here have ideas.

**Comment by igrep** [comment]
Okay, I'll look for a folk who can guide you.

Ref: Here's the English address of the venue: 20-17 Udagawacho, Shibuya City, Tokyo 150-0042
Note [Google Maps says it's Docomo Shop](https://www.google.co.jp/maps/place/Docomo+Shop+Shibuya+Shop/@35.6610476,139.69829,17z/data=!3m1!4b1!4m5!3m4!1s0x60188ca86c6fc251:0xe2e1ca133b4c4f0e!8m2!3d35.6610433!4d139.7004787?hl=en), but it's at the 8th floor of the same building with Docomo Shop.

**Comment by as-capabl** [comment]
到着空港を聞いておくと良いと思います

**Comment by igrep** [comment]
@ekmett Which airport and when are you going to arrive at?
Haneda or Narita? At the day of the event (Nov. 9), or before that?

c.c. @kazu-yamamoto (I'm currently asking for kazu now)

**Comment by igrep** [comment]
@ekmett ping. If you are afraid of writing your flight plan here, send it me via DM on Slack or other.

**Comment by ekmett** [comment]
I land in Tokyo at Wed, Nov 06, 2019 02:45 PM via HND.

I depart Tokyo at Mon, Nov 11, 2019 09:50 AM via NRT.

So there should be plenty of slack in my schedule.

**Comment by igrep** [comment]
So you'll go to the venue from the hotel, and you haven't decided the hotel to stay yet, right?
IMO Shinagawa (品川: the "Three-boxes-three-lines Station") might be the best station for your hotel.
Because you can go from/to Shinagawa to/from Haneda, Shibuya (the venue of Haskell Day 2019), and Nihonbashi (one of the nearest station from the venue of https://fpc2019japan-event.peatix.com/) **with almost no transition** (see below for ref.).

- [Haneda to Shinagawa](https://www.google.co.jp/maps/dir/haneda+airport/shinagawa+station/@35.617045,139.7241944,13z/data=!4m14!4m13!1m5!1m1!1s0x6018640ba43192e3:0xd32c3a9d146f8df!2m2!1d139.7798386!2d35.5493932!1m5!1m1!1s0x60188a5a6e148775:0x9a45c347f706db70!2m2!1d139.7387597!2d35.6284713!3e3?hl=en)
- [Shinagawa to the venue of Haskell Day 2019](https://www.google.co.jp/maps/dir/Shinagawa+Station,+3+Chome-1+Takanawa,+Minato+City,+Tokyo/%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%EF%BC%92%EF%BC%90+TECH+PLAY+SHIBUYA/@35.6390343,139.7020458,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x60188a5a6e148775:0x9a45c347f706db70!2m2!1d139.7387597!2d35.6284713!1m5!1m1!1s0x60188ca86c6cae51:0x7013b18cfb99f4b4!2m2!1d139.700351!2d35.661005!3e3?hl=en)
- [Shinagawa to the venue of FPC 2019](https://www.google.co.jp/maps/dir/Shinagawa+Station,+3+Chome-1+Takanawa,+Minato+City,+Tokyo/%E6%9D%B1%E4%BA%AC%E9%83%BD%E4%B8%AD%E5%A4%AE%E5%8C%BA%E6%97%A5%E6%9C%AC%E6%A9%8B%E8%8C%85%E5%A0%B4%E7%94%BA%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%98+FinGATE+KAYABA/@35.6553512,139.7413769,14z/data=!3m1!4b1!4m14!4m13!1m5!1m1!1s0x60188a5a6e148775:0x9a45c347f706db70!2m2!1d139.7387597!2d35.6284713!1m5!1m1!1s0x6018895a30855555:0xbed0608c92909b9c!2m2!1d139.7788269!2d35.6801504!3e3?hl=en)

I don't know much about hotels there, but there should be plenty of hotels around Shinagawa.

**Comment by kazu-yamamoto** [comment]
@ekmett I live in Shinagawa. If you need help, please let me know.
If you wish, I will take you from HND to your hotel on Nov 6.

**Comment by kazu-yamamoto** [comment]
Keikyu Ex Inn Shinagawa should provide large and comfortable rooms in reasonable price:
https://www.keikyu-exhotel.jp/hotel/shinagawa/en/index.html

**Comment by ekmett** [comment]
I seem to have waited too long to book at that hotel. Looking for alternate accomodations in the area.

**Comment by ekmett** [comment]
I found something nearby. 

@kazu-yamamoto, your offer of some help getting to the hotel from the airport is much appreciated. I've definitely under-planned this trip so far.

**Comment by kazu-yamamoto** [comment]
@ekmett Please tell me your flight number. I will show up at Haneda airport on 6 Nov.

**Comment by ekmett** [comment]
UA875

**Comment by kazu-yamamoto** [comment]
OK. Please find a name plate of "ekmett" at the exit. See you seen.

**Comment by ekmett** [comment]
Thank you both so much for all of your assistance! I had a great time in Japan. If you choose to do another Haskell Day next year, let me know and I’ll try my best to make it back!

**Comment by ekmett** [comment]
I suppose you can feel free to mark this “issue” as closed. Thanks again.

**Comment by igrep** [comment]
Thank you very much too! I'll close.

**Comment by igrep** [comment]
@ekmett Can you upload your talk's slides in Haskell Day 2019 and share their URL here?

**Comment by ekmett** [comment]
I didn't really have much in the way of slides, but here you go.

**Comment by ekmett** [comment]
https://drive.google.com/file/d/1J3P5kn1Vbg_BPkQBlOfJ2jAwUfhGBNjl/view?usp=sharing

**Comment by igrep** [comment]
@ekmett Thank you! But can you convert it to some other format which Google Drive can show (e.g. PDF)? It seems that Google Drive can show only the first page of it.

**Comment by ekmett** [comment]
https://drive.google.com/file/d/1bwYO66xUKeHyR4YCNm_1C82JlDNQLUXv/view?usp=sharing

**Comment by igrep** [comment]
Thanks! I confirmed I can see it!
