### ISSUE TITLE
タイムテーブル

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#11]
現状のタイムテーブル案。

- 🆙 難易度がどこまで当てになるかわからないので（去年も実際のところ一致してなかったしね）、ざっくりテーマ別に順番を整えてみました。
    - 概ねHaskell自体のテクニックの話から、Haskellの応用例の話に変わるようにしているつもりです。

Time|Title|Speaker|Category
---|---|---|---
10:00|👐開場|
10:30|🎊Opening|
10:45|関数型(function type)を見つめるプログラミング|山下伸夫（聖徳大学）|Basics
11:15|HKD(Higher Kinded Datatype)|fumieval|Advanced Techniques
11:45|🍱Lunch Break|
13:15|GHC・阿鼻叫喚のDerivingストラテジー|aiya000|Advanced Techniques
13:45|HaskellメタプログラミングによるEgisonのパターンマッチの実装|江木聡志 (楽天技術研究所) |Advanced Techniques
14:15|☕️Break|
14:30|関数と型で理解する自動微分|lotz|Math (Real WorldよりのAdvanced Techniques)
15:00|GHCJS による Web フロントエンド開発|チェシャ猫|Real World (Advanced TechniquesよりのReal World)
15:30|☕️Break|
15:45|Haskell で作る競技型イベントの裏側|松原信忠|Real World
16:15|大規模数値計算を支える Haskell ── Pragmatic Haskell in Large-Scale Numerical Computation|石井大海（DeepFlow株式会社）|Real World
16:45|☕️Break|
17:00|Special Talk: TBD|Edward Kmett|Special Talk
17:30|⚡️Lightning Talks (当日募集します！)|
18:10|🍻Closing・After Party|
20:30|👋撤収|

**Comment by igrep** [comment]
補足: 現状のタイムテーブル案は、セッション時間を最も増やす想定で計算しています。
現状数は足りていないので、開始を遅らせるとか、LT時間を増やすという方向で対応するかも知れません。（あるいは休憩時間を増やすとか）

**Comment by igrep** [comment]
あ、あとこのタイムテーブル、短時間のスポンサーセッションが入ってなかった。

**Comment by as-capabl** [comment]
LTをやってみたいと思っていて、公募開始のタイミングを狙ってます

**Comment by igrep** [comment]
当日会場で募集しますのでぜひ！

**Comment by igrep** [comment]
イベントページで公開までしたので、あとは適宜対応するということでclose
