### ISSUE TITLE
スポンサー関連諸々

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#12]
https://github.com/haskell-jp/community/issues/8 の続きにしようかと思いましたが、長くなりそうなのでスポンサー関連のタスクに関してのみこちらに移します。

- 集金方法: 口座を新しく作る？IIJ広報に相談するか。
- 宣伝方法の確認・確定
    - [x] 株式会社インターネットイニシアティブ
    - [x] マーベリック株式会社
    - [x] 株式会社クリプタクト
    - [x] 株式会社HERP
- ロゴ掲載（使用してよい画像のURLなどを尋ねる）
    - [x] 株式会社インターネットイニシアティブ
    - [x] マーベリック株式会社
    - [x] 株式会社クリプタクト
    - [x] 株式会社HERP
- 請求書の発行
    - [ ] 株式会社インターネットイニシアティブ
    - [ ] マーベリック株式会社
    - [ ] 株式会社クリプタクト
    - [ ] 株式会社HERP
- 振り込み確認
    - [x] 株式会社インターネットイニシアティブ
    - [ ] マーベリック株式会社
    - [ ] 株式会社クリプタクト
    - [ ] 株式会社HERP
- 領収書の発行
    - [ ] 株式会社インターネットイニシアティブ
    - [ ] マーベリック株式会社
    - [ ] 株式会社クリプタクト
    - [ ] 株式会社HERP
- チラシ・ノベルティー受け取り
    - [x] 株式会社インターネットイニシアティブ
    - [x] マーベリック株式会社
    - [x] 株式会社クリプタクト
    - [x] 株式会社HERP

**Comment by igrep** [comment]
現在スポンサーとして名乗り挙げていただいた企業様

- 株式会社インターネットイニシアティブ:
    - 協賛金: 5万円
    - 宣伝方法: カタログ・パンフレット・ノベルティーの配布
- マーベリック株式会社:
    - 協賛金: 15万円
    - 宣伝方法: チラシの配布
- 株式会社クリプタクト:
    - 協賛金: 5万円
    - 宣伝方法: チラシの配布
- 株式会社HERP:
    - 協賛金: 10万円
    - 宣伝方法: チラシ・ノベルティーの配布

**Comment by kakkun61** [comment]
IIJ について

> 1. 翌日以降、参加者リストの提出
> 2. お渡しした額面（5万円）での、領収書手配

**Comment by igrep** [comment]
@kakkun61 と口頭で確認したメモ

- 請求は、飲食物を一通り決め、発注して領収書をもらってから行う。
- 少なくともIIJからいただくお金については、（余った分を返却しやすくするため）発注先の業者に直接IIJ向けの領収書を発行してもらう

**Comment by fumieval** [comment]
ケータリングの見積もり( https://github.com/haskell-jp/community/blob/HD19/HaskellDay/2019/banquet/%231%E3%80%9020191109%E7%9B%B4%E3%82%B1Y1%20%E3%81%8A%E8%A6%8B%E7%A9%8D%E3%82%82%E3%82%8A%E3%80%91Haskell%20Day%202019%20%E5%BE%A1%E4%B8%AD.pdf )が出たので早速注文をしました。請求書、領収書ともに分割が可能とのことなので、発行され次第マーベリック御中には15万円、HERP御中に10万円分の請求書と領収書をそれぞれ送付します。残りの8500円はソルバーに投入してから決めます

**Comment by igrep** [comment]
✍️ スポンサー企業のノベルティー・チラシなどは当日持ってきていただく

**Comment by kakkun61** [comment]
IIJ からあずかったもの

- 協賛金
  - @igrep 渡し済み
- 首さげ名札
  - 20個
  - #25
- 頒布物
  - チラシ
    - 2種類
  - クリアーファイル

**Comment by kakkun61** [comment]
@igrep 昨日あずかった領収書と残額の封筒を IIJ 広報に渡したんですが、足して5万円になっていないそうです。（自分は中身を確認していませんでした。）
何か心当たりありますか？

**Comment by kakkun61** [comment]
（口頭解決）
PDF でもらった領収書も IIJ 宛てだったんですね

**Comment by igrep** [comment]
特に残課題はないはずなのでclose
