### ISSUE TITLE
Haskell Day 2019 反省

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#17]
気づいたときに書いておこう。

**Comment by igrep** [comment]
TECH PLAYの参加枠を「抽選」にすると、後で「先着順」に変更できない。
抽選自体も完全に自動で行われるわけではなく、（ブラックリストにいる人などを外したりするために）手動でコントロールできるようになっている。connpassと大分毛色が違う。

**Comment by igrep** [comment]
☝️ の件、ややこしいことに「先着順」の別の参加枠を作ってからも「抽選制」に登録して枠があふれてしまうという事態が発生してしまった。
https://twitter.com/haskell_jp/status/1178918874063896576

**Comment by igrep** [comment]
スポンサー企業のロゴはイベントページ公開時に早くから載せるべきだった。

**Comment by igrep** [comment]
録画や配信にまで頭が回らなかったな...

**Comment by igrep** [comment]
ekmettさんがオープニングからいらっしゃるなら、英語の資料を用意すべきだった

**Comment by igrep** [comment]
- 受付時、受付番号を尋ねることをもっと早くからアナウンスすべきだった
- 当日の分担を早くやるべきだった
    - 早めに来てもらうよう依頼しないといけなかったりするので
- 想像以上に文字の大きさについてシビアにならないと見にくくなってしまうので次回はアナウンスを

**Comment by konn** [comment]
タイムテーブルを参考に来る人もいるので、なるべく巻きではなく時間通りに進行したほうがよい

**Comment by igrep** [comment]
受付を横向にすることで発表を聞きながら受付できるようにできた

**Comment by matsubara0507** [comment]
https://qiita.com/advent-calendar/2019/haskell の宣伝をしても良いのではなかろうか（天才）

**Comment by igrep** [comment]
名札をできれば用意すべきだったかも（受付が済んだ人かどうかがわからない！

**Comment by fumieval** [comment]
会場のフロアに余裕がなく、ケータリングの準備を難しくしていた

**Comment by igrep** [comment]
時間が押している / 巻いている場合にプレゼンテーションタイマーをいい感じに調整すべきだったかも知れない

**Comment by nobsun** [comment]
自分のPCからプロジェクターに出力できなくて焦った(いままで1度も経験してない)．とはいえ，予備機を準備するのも手間．ちゃんと想定して次善の策をもっておくことが必要（反省）

**Comment by igrep** [comment]
私個人の問題ですがTwitterやら周りの様子が気になって発表にあまり集中できませんでした...。
去年はそんなことなかったのになぁ。

**Comment by as-capabl** [comment]
質問者へのマイク渡しですが、誰に渡すのか自己判断でやろうとすると、かなりもたついてしまいました。

**Comment by igrep** [comment]
確かに、そのあたりの打ち合わせが不足していました。 🙇

**Comment by igrep** [comment]
何度か懇親会で触れましたが、ちょっと全体的に難しい発表が多くなってしまいました。
まあ、今回は難易度調整を意図的にサボったのでしょうがないといえばしょうがないですが...

**Comment by igrep** [comment]
~アンケート回答数が36件しかなかった 😥~
下記の通りTECH PLAY管理画面からメッセージを送ったのでまだ増えるはず 🙏

**Comment by fumieval** [comment]
LT終了後即座に(?)懇親会が始まったのでアンケートを記述する余裕がなかったのかもしれませんね…

**Comment by kakkun61** [comment]
今からでも Connpass システムで参加者宛てにアンケートのお願い送るといいかも？

**Comment by igrep** [comment]
connpassじゃなくてTECH PLAYね...! 🙏 
今参加者宛メッセージ書いてます。テスト送信したので @kakkun61 とかの元には届いているはず。
このまま14:00に送信するよう設定しました（TECH PLAYの仕様上必ず予約して配信することになります）

**Comment by kakkun61** [comment]
来てました。よさそう。
（Tech Play も Connpass システムなので云々

**Comment by igrep** [comment]
TECH PLAYの管理画面曰く出席者数は96名とのことで、スタッフの数を合わせれば懇親会の食事を110名向けにしたのは概ねあたりだった 👍 
実際のところ全員が懇親会に参加したわけじゃないので、もう少し少なくてもよかっただろうけど。実際一部の料理が余ってたしね。

**Comment by igrep** [comment]
当日Slackにだけ書いていた反省:

- 床を拭くものとかもこちらで用意すべきだったか
- ノベルティーの配り方はもうちょっと工夫すべきだった。かなりチラシが余り気味だったようなので...

**Comment by igrep** [comment]
領収書の宛名は会社名で書けなかったか、というクレームがIIJ広報部から来ました... 🙇  @fumieval

**Comment by fumieval** [comment]
逸酒創伝の領収書ですよね？作り直すわけにもいかないのでとりあえず25,536円は返金します…

**Comment by igrep** [comment]
あっ、今回は大丈夫です。とのことで.... 💦

**Comment by fumieval** [comment]
ご迷惑をおかけしました。

**Comment by kakkun61** [comment]
ツリー構造になっていた方が見やすいと思ったので Google ドキュメントにまとめ直しました。

https://docs.google.com/document/d/1viNvVjtMxUYCzCTSK-vo7f7YwtyXI6Y3SF9AYEOitH0/

**Comment by kakkun61** [comment]
あと、よかった点は次もやるべきだしほめられるとうれしいので、よかった点も書きましょう

**Comment by igrep** [comment]
会計上の都合により、懇親会の参加人数はなるべく正確に把握しておくべきだったようです。
