### ISSUE TITLE
アンケートの作成

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#19]

**Comment by igrep** [comment]
@matsubara0507 去年と同様お願いしてもいいでしょうか？
今年はスポンサーであるクリプタクト様からの要望があり、 👇 の質問と注記を足してください。

- 質問
    - エンジニア経験年数
    - 主な得意分野（例：Web、機械学習、ブロックチェーン、金融IT）
    - その他最近注目のテクノロジー
- 集計結果をスポンサー企業と共有すること

補足: 関連するslackのメッセージ:
- https://haskell-jp.slack.com/archives/CN3P057K8/p1572243181047200
- https://haskell.jp/slack-log/html/CN3P057K8/3.html#message-1572243181.047200

**Comment by matsubara0507** [comment]
今気付いた(笑)
やっておきます :+1:

**Comment by matsubara0507** [comment]
@igrep 
アンケート作りました。
https://docs.google.com/forms/d/e/1FAIpQLSeQl3Ce4WE-PnDUXnBdDMrCyJXAUUWc5A7RWAqY0iA2EtWfjA/viewform?usp=sf_link
(アンケートを回答する形になってますが、当日事前の回答は破棄します）

前回のアンケート項目
- Haskell を始めた頃
- Haskell 歴
- 日本語 Haskell 書籍の読書歴 (補充しました、wiki はあとで更新します)
- 各セッションの感想

と、上記要件項目を簡単に足した感じになってます。
最初の注記とかもそれっぽく変えました。

**Comment by igrep** [comment]
ありがとうございます！選択肢まで考えていただいてめっちゃ助かります！ 👍 

いくつか気になった点を。

#### 冒頭の導入分について

> セッションに関する感想の質問は Slack で共有します。

「セッションに関する感想は Haskell-jpのSlack Workspaceのみで共有します。」で。
- 細かいところですが共有するのは質問そのものではなく質問の回答（感想）なので。
    - これについては他のページについても同様です
- 共有する範囲を明確に

> それ以外の質問はスポンサー・運営で共有したのちに Haskell-jp Blog で公開します。

「それ以外の質問の回答はスポンサー・運営で共有したのちに Haskell-jp Blog で公開します。」
- 同じく共有するのは質問の回答なので

#### 各ページの「自由記述」について

例えば「その他、Haskell Day 2019について何かコメントがあればください」のように、もう少し意図を明確にした方が書きやすいかと思います。

#### [セッション] Haskellを導入した話とHRRの紹介

去年のセッションが残ってしまっています。

**Comment by matsubara0507** [comment]
実は「のみ」ってのはあえて抜いてて
なぜかっていうと haskell-jp/slack-log でインターネット公開されるようなもんだからなんですけど、これってどうします？

**Comment by matsubara0507** [comment]
とりあえず、指摘してもらった箇所は修正しました 👍

**Comment by igrep** [comment]
ああー、そうか、なるほど💡
じゃあ「のみ」ではなくて「回答者が特定されない形で」といった方が適切だしそうすべきですな。

2019年11月4日(月) 11:59 MATSUBARA Nobutada <notifications@github.com>:

**Comment by matsubara0507** [comment]
> 各セッションに関する回答は Haskell-jp の Slack Workspace にて共有します。
それ以外の質問の回答はスポンサー・運営で共有したのちに Haskell-jp Blog で公開します。
いずれの場合も個別の結果ではなく、回答者が特定されない形で集計結果のみを共有・公開します。
>
> また、どの質問も回答必須ではないのでお気軽にご回答ください。

って具合に直しました。

**Comment by igrep** [comment]
いいと思います！

続けて済みません、2ページ目以降の

> セッションに関する感想の質問は Slack でのみ共有します。

という記述は冒頭との一貫性を考えて削除しちゃいましょう。
「感想の質問」といっているのが自由記述だけなのかそれ以外も含めてなのか曖昧ですし、かといって冒頭の記述を繰り返すのも冗長ですし。

それと、2ページ目以降の「自由記述」という質問も「その他コメント」と書いた方が書いていただきたいことがわかりやすいと思います。

**Comment by matsubara0507** [comment]
こんなとこにも書いてあったか 🙇

**Comment by matsubara0507** [comment]
変えました〜

**Comment by igrep** [comment]
@matsubara0507 ありがとう！ 👍 
重ねて済みません！クリプタクトの  @smasuda さんより「得意なプログラミング言語は？」という質問を追加して欲しいという依頼があったのでお願いしたいです 🙏 

選択肢は以下の通りでお願いします。

```
Assembly
C
C#
C++
Clojure
Elm
Erlang
F#
Go
Groovy
Hack
Java
JavaScript
Julia
Kotlin
Lua
MATLAB
Objective-C
OCaml
Perl
PHP
PureScript
Python
R
Ruby
Rust
Scala
Shell
Swift
TypeScript
VBA
VB.NET
```

※https://haskellweekly.news/survey/2019.html を参考に修正しています。slackではVB.NETについても修正しようかと検討してましたが、よく考えたらVBAだって正式名称は「Visual Basic for Application」だし、より通じそうな名前に寄せました。

**Comment by matsubara0507** [comment]
+Haskell ですかね？w

**Comment by igrep** [comment]
ほんまや…😰
ありがとう。加えておいてください…🙏

2019年11月6日(水) 13:16 MATSUBARA Nobutada <notifications@github.com>:

**Comment by matsubara0507** [comment]
更新しましたー 👍

**Comment by igrep** [comment]
いいと思います！
Ekmettさんの発表タイトルがわかったときに更新するのだけ忘れないようにしましょう！
（多分当日その場になってしまいますが。。。 😞 ）

**Comment by kakkun61** [comment]
ツイートしました https://twitter.com/haskell_jp/status/1193005016753131520
