### ISSUE TITLE
スタッフ用Tシャツ

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#20]
スタッフ向けの目印として

**Comment by matsubara0507** [comment]
時期的にTシャツきるか微妙ですねw
（本質はそこじゃないだろうけど）

**Comment by kakkun61** [comment]
思いつき駆動だー ｳｺﾞｺﾞｺﾞｺﾞ

**Comment by kakkun61** [comment]
11リアクションあったので作る予定にした。

https://haskell-jp.slack.com/archives/CAXQ09PN2/p1570687053012000

とりあえず M サイズ 10着・L サイズ 10着を考えている。

今しがた見積り依頼した。

https://www.p1-intl.com/

**Comment by kakkun61** [comment]
見積り来ました。
自分がもたもたしていたので割増になって1着当り2600円ぐらいです。

もし今後同じ版を使って依頼すると、おそらく製版代は要らなくなるはず。

```
■御見積金額: ￥51,920    （約 2,596 円／１点）
 
■明細:
▼プリント色：未定
・・商品・・
5745-01:UnitedAthle (ユナイテッドアスレ) 4.7オンスファインジャージーTシャツ（アダルト）
  ネイビーM   10枚 × ￥616 = ￥6,160
  ネイビーL   10枚 × ￥616 = ￥6,160
 
前面(胸中央上)：3色
・・加工賃・・
シルクプリント加工
  胸中央上:製版代/大（28x33cm以内）   3版 × ￥8,800 = ￥26,400
  胸中央上:プリント代/Tシャツ/カラー生地 3色   20枚 × ￥572 = ￥11,440
 
特急料金   1件 × ￥8,800 = ￥8,800
 
10月31日迄☆　*シルク加工　1色分のプリント代無料キャンペーン　≪オプション料金は除く≫
1ヶ所1色目無料キャンペーン
  プリント代/1ヶ所   -20枚 × ￥352 = ￥-7,040
 
------------------------------
小計：￥51,920
通常P使用：0p
プレミアムP使用：0p
送料：￥0
------------------------------
合計金額：￥51,920
```

**Comment by igrep** [comment]
口頭のとおり、懇親会予算のあまりは期待できないので、 https://github.com/hasmoku/fund から拠出しつつ原則欲しい人が買うという形にしましょう。
なので15枚で。

**Comment by kakkun61** [comment]
### 集計

:zero: 不要 :one: S :two: M :three: L :four: XL :five: XXL
![t-shirt](https://user-images.githubusercontent.com/282593/67864618-3b81a200-fb69-11e9-89af-6f3000c407fe.png)

S 3, M 0, L 6, XL 1
（L が6なのは自分の分を追加しているから。）

ここまでで10。残りの5は M 3、L 2 に。

計 S 3, M 3, L 8, XL 1

### サムネイル

![t-shirt-thumbnail](https://user-images.githubusercontent.com/282593/67865876-679e2280-fb6b-11e9-999b-dc96143e850b.png)

生地はネイビー、ロゴの色は DIC カラーに変更してあるので微妙に変わっている。 CC: @fumieval

**Comment by kakkun61** [comment]
一応書いておくと、固定費が大きいので、枚数を減らすと単価が上がる

**Comment by kakkun61** [comment]
こちらで発注しました。

```
◆お見積もり（税込）
■御見積金額: ￥47,740    （約 3,183 円／１点）
■明細:
▼プリント色：DIC 351s　DIC 263s　DIC 2013s*
・・商品・・
5806-01:UnitedAthle (ユナイテッドアスレ)4.0ozプロモーションTシャツ
  ネイビーS   3枚 × ￥506 = ￥1,518
  ネイビーM   3枚 × ￥506 = ￥1,518
  ネイビーL   8枚 × ￥506 = ￥4,048
  ネイビーXL   1枚 × ￥506 = ￥506
 
前面(胸中央上)：3色
・・加工賃・・
シルクプリント加工
  胸中央上:製版代/大（28x33cm以内）   3版 × ￥8,800 = ￥26,400
  胸中央上:プリント代/Tシャツ/カラー生地 3色   15枚 × ￥803 = ￥12,045
 
特急料金   1件 × ￥8,800 = ￥8,800
 
10月31日迄☆　*シルク加工　1色分のプリント代無料キャンペーン　≪オプション料金は除く≫
1ヶ所1色目無料キャンペーン
  プリント代/1ヶ所   -15枚 × ￥473 = ￥-7,095
------------------------------
小計：￥47,740
通常P使用：0p
プレミアムP使用：0p
送料：￥0
------------------------------
合計金額：￥47,740
```

![](https://user-images.githubusercontent.com/282593/67925043-86e19200-fbf5-11e9-9d9c-0041d9ad93cb.gif)

**Comment by kakkun61** [comment]
私の自宅に8日に届くので持って行きます。

**Comment by kakkun61** [comment]
シルクスクリーン用の版は1年間保管してもらえるので今後同じ柄で作るときはだいぶやすくなる。

計算がじゃまくさくなるので今回の出費は今回の購入者で分割します。今後と比較して高くなるのはごめんなさい。

**Comment by kakkun61** [comment]
単価3183円ですが簡単のため3200円集金します。差額は hasmoku 基金に貯めます。

サイズ | 発注数 | 予約 | 残数
:---:|---:|:---:|---:
S | 3 | syocy, y_taka_23, nakaji-dayo | 0
M | 3 | - | 3
L | 8 | kakkun61, lotz, mr_konn, igrep, aiya000, as_capabl | 2
XL | 1 | matsubara0507, nobsun | -1

### 集金済み

 - [x] S syocy
 - [x] S y_taka_23
 - [x] S nakaji-dayo
 - [x] L lotz
 - [x] L mr_konn
 - [x] L igrep
 - [x] L aiya000
 - [x] L as_capabl
 - [x] XL matsubara0507
 - [ ] XL nobsun

**Comment by kakkun61** [comment]
@igrep [hasmoku 基金](https://github.com/hasmoku/fund)から15740円もらって、残った T シャツの所有権を渡す、ということで。

名目 | 価格
---|---:
(1) T シャツ会社へのしはらい | 47740
(2) 売り上げ（9×3200） | 28800
(3) 自分の分しはらい | 3200
(1) - (2) - (3) | 15740

**Comment by igrep** [comment]
✅ https://github.com/hasmoku/fund/commit/f117c7d1e2ce2ad72c11c7c0487ece9bc213e9af

**Comment by nobsun** [comment]
あ．T-shirt うけとり(しはらい)わすれた．

**Comment by kakkun61** [comment]
@nobsun もくもく会かどこかで会う機会があれば事前に伝えてもらえれば持って行きます。

ただ、最終的な XL 希望者は2名でしたが発注時に1票だったので XL はもうないです。

もう要らないということであればそれでも大丈夫です。

**Comment by nobsun** [comment]
それでは，今回は不要ということで．

**Comment by igrep** [comment]
必要な方にはすべて配り終えたと言うことで今回はclose
