### ISSUE TITLE
司会で話すこと、進行の仕方

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#21]
私がekmettさんを案内する関係で、司会を当日することができなさそうなのでほかのスタッフに依頼するため、当日話すことなどについて議論するissue

**Comment by igrep** [comment]
Haskell Dayの司会の主な仕事は以下の通り:

1. オープニングトーク: 参考: https://the.igreque.info/slides/2018-11-10-haskellday.html
    - 会の趣旨の説明
    - [x] 会場諸注意: TECH PLAYさんに確認します（先ほど問い合わせました）
    - Haskell-jpそのものの宣伝
    - **スポンサー各社の紹介**
         - 順番は https://techplay.jp/event/727059 に載せた順番そのままで。
1. 発表中
    1. 🕥 タイムキーパー: 発表時間は普通のセッションは30分、LTは5分。**いずれも質問時間を含めて！** 時間を守るためになるべく強制的に切っちゃってください！
    1. 各発表開始時に発表者名とタイトルを述べる
    1. 👏 各発表終了時に質問者を選んだり、最後の拍手を参加者に求めたり
1. クロージング
    1. 終了の挨拶、懇親会が始まる、程度の連絡

**Comment by igrep** [comment]
TECH PLAYより回答をいただきました。以下抜粋します。

> ここまで細かく記載する必要はないですが、過去イベント状況に応じて
必要であれば文言アレンジの上、追加いただけますと幸いです。

> ・ビル内、火気厳禁であること（喫煙不可）
・他フロア（８F以外）の利用不可（お手洗いなどの他フロア利用も不可です）
・カーペットエリアを使うようであれば、土足・飲食厳禁
・冷蔵庫に入れてあるTECH PLAY在庫のドリンクの持ち出し不可
・エレベーター等、他フロアとの共有部分での飲食不可
・Wifi情報　（SSID：TECH PLAY　PASS：Techplay0614）

**Comment by igrep** [comment]
会場諸注意についてTECH PLAYより回答をいただきました。以下、一部修正して抜粋します。

> ここまで細かく記載する必要はないですが、過去イベント状況に応じて
必要であれば文言アレンジの上、追加いただけますと幸いです。

> ・ビル内、火気厳禁であること（喫煙不可）
・他フロア（８F以外）の利用不可（お手洗いなどの他フロア利用も不可です）
・カーペットエリアを使うようであれば、土足・飲食厳禁
・冷蔵庫に入れてあるTECH PLAY在庫のドリンクの持ち出し不可
・エレベーター等、他フロアとの共有部分での飲食不可
・Wifi情報　（※）

※WiFi情報についてはそんなに秘匿するべき情報じゃない気もするけど念のためここには書かないでおきます

**Comment by igrep** [comment]
@nakaji-dayo と、言うわけで、おそらく当日私はオープニングの際会場にいない可能性が高いので、 ☝️ の2つの発言に従って、オープニングトークで使用するスライドを作っておいてください。 :pray:

**Comment by nakaji-dayo** [comment]
@igrep リストアップと確認ありがとうございます！

- [ ] オープニングトークの準備します

- タイムキーパー
  - 確かタブレットで時間の表示とかやってましたっけ？

**Comment by igrep** [comment]
そうですね。手段は任せますが、なるべく発表者にとって見やすい形になっていた方がいいです。
「プレゼンテーション タイマー」で検索すると割と使えそうなものがヒットするのではないかと思います。

**Comment by nakaji-dayo** [comment]
とりあえずスライド作りました。
https://docs.google.com/presentation/d/1mg6SKo0r8G4lpWMREkLQA54cotkv6Kpybd1o2tWsPXo/edit?usp=sharing

@igrep 口頭でいくつか確認させてください

- スポンサー企業紹介で、企業名以外に触れるべきことはないか
  - (ブースとか配布物とか
- 途中入退場の案内が必要か
- 当日LTについての説明がオープニングで必要か
  - 募集の仕方とか、多数だった場合の選び方とか(?)
- 会場諸注意
  - 不要な項目あるかも
  - 写真撮影など
- HashTag
- 質問者にマイク渡しに行くの手伝ってほしい(スタッフにあまりがあれば

**Comment by nakaji-dayo** [comment]
・どの企業も、チラシとノベリティの配布
　・会場の後ろに置いている
・入退場自由（受付も不要
・当日LT
　・ホワイトボードがあるので、そこに書いてもらう＞休憩時間
　　・応募者多数はじゃんけん
・twitter hash tag #haskellday


判明した役割
- 質問者にマイク渡す
- LTの受付

**Comment by igrep** [comment]
LTのことで思い出しましたが、やっぱりCoCが必要そうですね... 😥 
ある種の任意コード実行なワケなので、何かしら保護するために規約を用意します。

**Comment by igrep** [comment]
@nakaji-dayo 
スライドありがとうございます！
いくつか気になった点を。主に文字が多いスライドについてです：

- 「主催グループの宣伝」という見出しは冗長ではないかと。単に「日本Haskellユーザーグループについて」と書いて主催であることは口頭で言えば伝わるのではないかと思います
- 「Lightning Talk募集について」: 「当日募集です！」という情報は、同じく冗長なので当日に書かなくてもいいんじゃないかと思います。口頭で言う分にはよいかと思いますが
- ハッシュタグが手元の環境で見ると途中で行が切れちゃってますね... おそらく中嶋さんの手元では問題ないのだと思いますが、念のため

**Comment by nakaji-dayo** [comment]
@igrep レビューありがとうございます！
今日中に修正します！

**Comment by nakaji-dayo** [comment]
@igrep 修正しました！

> 「主催グループの宣伝」という見出しは冗長ではないかと。単に「日本Haskellユーザーグループについて」と書いて主催であることは口頭で言えば伝わるのではないかと思います

簡潔にしました。

> 「Lightning Talk募集について」: 「当日募集です！」という情報は、同じく冗長なので当日に書かなくてもいいんじゃないかと思います。口頭で言う分にはよいかと思いますが

削除しました。

> ハッシュタグが手元の環境で見ると途中で行が切れちゃってますね... おそらく中嶋さんの手元では問題ないのだと思いますが、念のため

ありがとうございます。こちらでは問題なさそうなので放置しました。

**Comment by igrep** [comment]
いいと思います！ 👍
