### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#23]
正直なところ敬遠してましたが、やっぱりCoCは必要そうです。
幸い、 https://2019.scalamatsuri.org/ja/code-of-conduct/ などがそのままコピペしてもいいライセンスでCoCを公開しているので、改変して使わせていただこうかと思います。

@nakaji-dayo オープニングトーク https://github.com/haskell-jp/community/issues/21 で、軽く言及していただきたいです。
最低限、

- CoCがあること
- CoCの概要
- LTに応募する人は必ず確認すること
- 守らなかった場合、注意や警告をした上で、「発表の中止、会場からの退出を強制することがある」こと

を書いてください。

**Comment by nakaji-dayo** [comment]
@igrep 了解です！

**Comment by igrep** [comment]
https://techplay.jp/event/727059 に張ったのでクローズ

**Comment by fumieval** [comment]
Haskell Day (2019)のCode of Conductはできましたが、他のプラットフォームやコミュニティレベルに拡張すべきかという問いがあるのをTrelloを見返していて思い出しました。
