### ISSUE TITLE
スタッフ用首掛け名札に付ける目印

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#25]
Tシャツ https://github.com/haskell-jp/community/issues/20 が間に合うのか不明なので、
https://github.com/haskell-jp/community/pull/24 では https://github.com/haskell-jp/community/blob/master/haskell-day-2019/CODE_OF_CONDUCT.md にはIIJ広報に貸していただく首掛け名札と書いておいた。
そこにHaskell-jpのロゴを描いた紙を差し込むのがよい目印になると思う

**Comment by igrep** [comment]
と、いうわけでその印刷する紙についての検討を @kakkun61 にお願いします。
大した数にはならないだろうから（A4 カラー数枚程度？）最悪執務室のプリンターで印刷するだけでもいいと思うけども。

**Comment by kakkun61** [comment]
IIJ から借りる首かけ名札にぴったりのサイズは 9.6cm×6.9cm だそう。
名刺サイズ 91mm×55mm でも。

この辺の紙がいいかと思います。
[なっとく名刺（標準・上質紙・アイボリー） - MT-JMN1IV](https://www.elecom.co.jp/products/MT-JMN1IV.html)

この紙の場合 IIJ-II の執務室の複合機ではプリントできないかもしれないけど。
と思ったけどいけそう。
[手差しトレイの用紙種類を設定したい DocuCentre-IV C5570/C4470/C3370/C2270 : サポート : 富士ゼロックス](https://www.fujixerox.co.jp/support/mf/dc4_c5570/contents/dc4_c5570_2802.html)

**Comment by igrep** [comment]
@kakkun61 口頭のとおり、今回は簡単に普通紙を印刷する、という方向でお願いします。
ロゴを使う場合は念のため @fumieval さんに一度共有してください。

**Comment by kakkun61** [comment]
単にスモールキャピタルの Arial で Staff と書いただけだけどこれで。 CC: @fumieval

![Haskell Day Staff](https://user-images.githubusercontent.com/282593/68484194-29e27d80-0280-11ea-9c5f-655bf111b076.png)

**Comment by fumieval** [comment]
問題なさそうです ✔️

**Comment by kakkun61** [comment]
プリント済み

自分は持って行きますが、誰かもはさみ持って来てくれるとはかどります。

**Comment by kakkun61** [comment]
あとはイベント後の回収だけなのでクローズしておきます
