### ISSUE TITLE
残課題

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#27]
- #12 IIJから受け取ったお金と請求書・領収書を忘れていた @igrep @fumieval 
    - あとは @fumieval が残りの領収書を送って、 @kakkun61 がすべての領収書とおつりを渡すだけ
    - [x] 領収書・請求書・残金を IIJ へ
    - [x] IIJ自ら請求書払いをする必要があるのを失念していたため、不足していたおつり8500円を @fumieval から @kakkun61 へ
- [x] #20 https://github.com/hasmoku/fund から不足分の支払い @igrep @kakkun61 
- [x] レポート記事、Togetter 誰がやろう🤔
    - 資料もレポート記事にまとめておきたい
- [x] IIJへ参加者リストの提出 @kakkun61 
- [ ] IIJ Engineer Blogへのリポート？
- [ ] 他にもある？

**Comment by kakkun61** [comment]
@igrep IIJ へ「参加者リストの提出」も追加お願いします

https://github.com/haskell-jp/community/issues/12#issuecomment-534405779

やります

**Comment by igrep** [comment]
:new: IIJ自ら請求書払いをする必要があるのを失念していたため、不足していたおつり8500円を @fumieval から @kakkun61 へ

**Comment by kakkun61** [comment]
IIJ へ領収書・請求書・残金渡しました

参加者リストも渡しました

**Comment by igrep** [comment]
> IIJ Engineer Blogへのリポート？

諸般の事情によりこの件はお蔵入りになってしまったので、残課題はもう終わったと見なしてcloseします。
