### ISSUE TITLE
「Haskell-jpもくもく会 @ オンライン」を可能な限り自動化しますか？

### ISSUE THREAD

**Issue by matsubara0507** [haskell-jp/community#28]
https://twitter.com/igrep/status/1276789802159857664
> 運営ガイドを更新して、ほぼ無人でも毎週開催できるよう整えた https://wiki.haskell.jp/Workshop/hasmoku/OrganizerGuide #hasmoku

もしかして、管理者無人でやりたいのかなと思い、仕組みを考えてみた。

今のところ管理者のタスクは

1. connpass ページの作成
2. Google カレンダーの登録
3. `@haskell_jp` として Twitter で告知
4. haskell-jp slack の mokumoku-online チャンネルで開催の呼びかけ（+ ツイート）
5. haskell-jp slack の mokumoku-online チャンネルで成果報告の呼びかけ（+ ツイート）
6. haskell-jp slack の mokumoku-online チャンネルで終了の呼びかけ

connpass は機械的にページを作るような API は無いので、手動にする他ないですが、それ以外は機械的に行えそうです（Twitter は厳しいかもしれないが）。

## 提案手法

PR をベースにする（新しいリポジトリを想定するが、別にここでもいい）。
(1) の connpass への登録のみは手動で登録して、hasmoku 開催 PR を作成する。
PR で追加するファイルは次のような YAML ファイル：

```yaml
# ファイル名は開催日: YYYY/MMDD.yaml
owner: [slack id]
connpass: [conpass のリンク]
```

PR がマージされると (2), (3) を GitHub Actions などで自動で行う。
開催日になったら (4), (5), (6) を[予約ツイート](https://developer.twitter.com/ja/docs/ads/creatives/api-reference/scheduled-tweets)・[リマインダー](https://api.slack.com/methods/reminders.add)として自動で登録する（GitHub Actions の Daily Cron などを使って）。 
ちなみに、開催時刻・終了時刻の取得は [connpass の API](https://connpass.com/about/api/) で行えます。

public リポジトリにすれば開催PRの作成は誰でもできますし、マージ自体はオーナーの igrep 氏などが行えばいいかと思います。
また、connpass の作成だけは可能な人が代わりにやってあげればそれで特に wiki に書いてあるような権限を渡す必要もなくなります。

### 実装イメージ

haskell-jp/mokumoku-operator リポジトリかなんかを作って CLI を Haskell で実装します。
CLI には各種 API のトークン（Twitter・Slack・Googleカレンダー）と設定ファイルのパスを渡します。
設定ファイルには次のような情報を書きます：

- Slack メッセージの投稿チャンネル
- Slack へ投稿するメッセージ
- Twitter のアカウントID
- Twitter へ投稿するメッセージ
- Google カレンダーのリンク

実装してできた実行ファイルを Docker イメージとして Docker Hub に置いておきます。
上記の開催PRを作るリポジトリでは設定だけを置いて、その Docker イメージを使い CI/CD で実行します。

**Comment by igrep** [comment]
いや、そこまで詳細に考えていただいたところ申し訳ないですが、現状完全に無人にしよう、とまでは考えてないです。
運営者の負担を減らすモチベーションはあるものの、「必ず参加する人」としての役割と、 [イベント当日: 開催中](https://wiki.haskell.jp/Workshop/hasmoku/OrganizerGuide#%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E5%BD%93%E6%97%A5-%E9%96%8B%E5%82%AC%E4%B8%AD) に書いてあるような役割は敢えて残していますし。

... と思ったけどこの案だと現状とやることは大して変わらないか。
今回策定したフローを少し楽にする程度のもののようなので、そこまで需要は高くないですが、あると確かに助かりますね。

> マージ自体はオーナーの igrep 氏などが行えばいいかと思います。

マージも別に誰がやってもいいですよ！（少なくとも現状の運営者はみんな権限を持っているはず！

**Comment by matsubara0507** [comment]
> マージも別に誰がやってもいいですよ！（少なくとも現状の運営者はみんな権限を持っているはず！

はい、その通りですね笑

試しに実装をしてみてて気づいたんですけど、 https://github.com/matsubara0507/mokumoku-operator
Twitter の予約投稿 API は Ad API で、特別な広告用アカウントじゃないと使えないっぽいですね。。。。無念。。。
まぁ hasmoku は 13:00-18:00 開催って決め打ちすれば簡単に実現できるけど、柔軟なのは今の Twitter API では難しいというのがわかったorz

**Comment by igrep** [comment]
CLIじゃなくて適当なサーバーで動かすしかないかな... 指定時刻に投稿するのはcronとかに任せて

**Comment by matsubara0507** [comment]
そうですね、CI/CD に任すのは難しいですね、予約投稿なしには。

**Comment by igrep** [comment]
若干スレ違いな気もしますが、次回の担当を決めるのに時間がかかっているので、その分も自動化できたらなぁ。

Googleカレンダーに登録した人の名前が残るので、それを見れば過去に誰が登録したかわかるので、それを元に、最後に担当してからの期間順に並び替えてメンションするbotなんて作るといいかもしれない。
この件の自動化でGoogleカレンダーへの登録方法が変わるとまた話が変わるかもだけど。

**Comment by igrep** [comment]
Slackにも書いた（+ 手順の自動化もした）とおり、 👇 のようなフローでIFTTTで一部自動化しました。
![image](https://user-images.githubusercontent.com/227057/104119925-58715200-5376-11eb-8b48-e0fbace9b16f.png)

**Comment by igrep** [comment]
動作確認できてないので次回暴発する可能性がありますが、Filterを追加して、日時が日本語で出るようにしました（IFTTT Pro版用の機能なので注意）。以下filterの内容:

```javascript
const title = GoogleCalendar.newEventFromSearchAdded.Title;
const start = new Date(GoogleCalendar.newEventFromSearchAdded.StartTime)
const month = start.getMonth() + 1;
const day = start.getDate();
const eventUrl = GoogleCalendar.newEventFromSearchAdded.Description;
Twitter.postNewTweet.setTweet(`${title} は ${month}月${day}日に行います。次回もお気軽にどうぞ！ #hasmoku #haskell
${eventUrl}`);
```

あっ、ダメだこれ、日時がもしかしてInvalid dateになるかも...

**Comment by igrep** [comment]
☝️ の問題がどうなるかは次回チェックするとして、さらに二つのフローを追加しました。
結果、「`3. 開始時刻（通常は13:00）になったら開催を告知するようSlackの#mokumoku-onlineチャンネルと、Twitterの@haskell_jpアカウントに予約します。` 」と、「`4. 終了時刻（通常は18:00）を過ぎたら成果報告の時間を告知するよう、同じくSlackの#mokumoku-onlineチャンネルと、Twitterの@haskell_jpアカウントに予約します。` 」の手順が省略できそうです！

つまりイベントページを作ってGoogle Calendarに登録した後は、「`2. イベント前日のお昼12時30分（お昼休みを取ってる人が多そうな時間なので）に告知するよう、Twitterの@haskell_jpアカウントに予約します。`」の手順だけでよくなりそう！ 🙌

**Comment by igrep** [comment]
@matsubara0507 
提案ありがとうございました！
ここで検討された修正は現在概ねIFTTTで実装できた上、 https://github.com/haskell-jp/community/issues/31 で再度整理したものと見えるので、closeさせていただきます。
