### ISSUE TITLE
Haskell Day 2020 代替イベント

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#30]
Haskell Day 2020 代替イベントを開催するかどう開催するか

**Comment by kakkun61** [comment]
開催するとしたらどういう形式で開催するか

時節柄オンサイトはできないのでオンラインで開催する

オンラインカンファレンスに使うサービスは何がいいか？

オンラインカンファレンスに必要な機能とは？

**Comment by kakkun61** [comment]
# リアルタイムでやる場合

こんな感じがいいのかな

1. 運営・発表者は相互通話ができるサービスを利用しつつ
2. 配信はライブ動画配信サービスを利用する

# 録画の配信

1. 発表者にそれぞれ事前に録画してもらう
2. 運営が編集し動画配信サイトにアップロードする

YouTube でいうところのプレミアム公開してその間は発表者がテキストで質問に答えるとかするのもありか

**Comment by kakkun61** [comment]
リアルタイムでやるとしても配信事故を考えると事前録画はあった方がいいな

難易度を考慮して録画の配信がよさそうか

**Comment by lotz84** [comment]
たしかに会って話せないのであれば無理にライブ配信にせず録画を集めたものでも良いのかなと思う一方で、  
イベントと称すからにはリアルタイムで配信されるコンテンツであった方が一体感が出て良さそうなので、個人的にはリアルタイムに一票入れたいです。  
司会者・発表者間をZoomで繋いでおいてその様子をYouTubeで配信するという形式は見かけますし、司会者がコメント等できたテキストを読み上げて発表者に答えてもらうというスタイルも良さそうですね。

**Comment by igrep** [comment]
FYI. 私が以前発表したWebAssembly nightでは、 https://streamyard.com/ を使ってライブ配信しました。
録画もライブも一長一短あるのでどちらでもよいとは思いますが！

**Comment by matsubara0507** [comment]
録画の良い例として、RubyKaigi Takeout 2020 （昨年のRubyKaigiの代替？）があります。
ぼくは全部を見てませんが、個人的には見やすくて良かったです（事故とかの類いがまずないので）。

**Comment by kakkun61** [comment]
リアルタイムだと相互コミュニケーションでわいわいできて楽しいので目指したい！ですが、初回はスモールスタートで安全牌を選びたい気持ちです🀄

2回目あるならやっていきましょう💪

**Comment by kakkun61** [comment]
サービスはどれにするか、動画配信だとまあ YouTube ですよね

YouTube 配信する際調べること

- haskell-jp の Google アカウント要るのか

**Comment by kakkun61** [comment]
アカウントとチャンネルは一対多で[チャンネルの移動](https://support.google.com/youtube/answer/3056283)もできるっぽい

**Comment by kakkun61** [comment]
[ブランドアカウント](https://support.google.com/youtube/answer/9367690)というのがあるのか なるほど

**Comment by nakaji-dayo** [comment]
録画 + プレミア配信、安牌かつイベント感もそこそこあり良さそうだと思いました。
プレミア配信後とかに、オンライン懇親会の場提供したりすれば、よりイベントっぽいですかね。

（プレミア配信使ったことなく話してますが、「投稿者と視聴者がリアルタイムで一緒に動画を楽しみつつ、かつチャット上でのコミュニケーションを楽しむことができます。」ってものらしいですね。

**Comment by winterland1989** [comment]
Hello there, This is Dong from the China Haskell community. 

I recently received a professional Haskell job at [EMQ](http://emqx.io/) which is an erlang shop, we're using Haskell in the next-generation products, and we want to push the Haskell engineer status quo forward. But the Haskell community in China is not yet strong, so may I ask if we can organize Haskell users in China to join the Haskell Day 2020 this time?

I've talked with @igrep on slack about this, it's really nice to know you guys are still trying to improve things. And we really to cooperate to push things forward. We can find sponsors, volunteers, translators here in China if you need. We can also give talks on Haskell practice here. 

So let's start get things  settled?

**Comment by igrep** [comment]
Thank you for getting interested in our next event, @winterland1989!
We can surely make Haskellers both in China and Japan more excited by cooperating for creating a meet up!
I want to hear all your thoughts on his suggestion!

冬さん（@winterland1989）、ご興味を持っていただいてありがとうございます！
協力してイベントを作ることができれば、中国と日本、双方のHaskell界を盛り上げられるでしょう。
提案についてご意見お願いします！

我欢迎你的合作。谢谢！（我一点一点地学汉语。）

**Comment by kakkun61** [comment]
I will form our Japanese members' opinions before our asking the Chinese community.

中国コミュニティとのやりとりの前にこっちで決められることを考えていきたいです。

とりあえず何を決めなきゃいけないかの項目をリストアップしていこうと思います。
下記の Google ドキュメントに自分の思い付くものを書き込んでみました。
不足があれば Google ドキュメントのコメントかこのイシューかにお願いします。

https://docs.google.com/document/d/110yycbk0T2IS74nQ84vELEMsXXGgRYdTFM4xSJmY734/

<details>
<summary>同内容をこちらにも記載します</summary>

# 背景

- COVID 19 の影響で Haskell Day 2020 が開催できなかった
- 初のオンラインで開催したい

# 配信方法

- 事前録画動画配信
  - Pros:
    - 当日トラブルが避けられる
    - 発表者が録り直すことで発表の質の向上
    - 事前の字幕準備ができる
  - Cons:
    - 一体感に欠ける
    - 視聴者とのインタラクティブが薄い
  - Counters of cons:
    - YouTube のプレミアム公開によってテキストベースのインタラクティブ
- リアルタイム配信
  - Pros:
    - 一体感
    - 音声映像によるインタラクティブ
  - Cons:
    - ノウハウ不足
    - 発表者の当日配信環境が必要
    - トラブルが起きるとオワる

# 時期

後でチャット・GitHub イシューなどで決めよう。

# 発表者募集方法

- 運営からオファー
  - Pros:
    - ある程度、発表の質などをコントロールできる
  - Cons:
    - 他に発表したい人がいる可能性
      - 在日もしくは日本語話者の Haskeller はほとんど Haskell-jp 内にいる可能性が高いが
- 公募
  - Pros:
    - Haskell-jp 外の発表希望者も応募できる
    - 公平性がある
      - 公募の選択にも公平性は必要
  - Cons:
    - 質などがコントロールできない
      - おそらく応募者にそのような人は少ないが

# スポンサー

募集する・しない。
かかる費用は。

# 行動規範

Haskell Day 2019 のもののままでよいか。

# 中国コミュニティとの連携

韓冬さんからのコンタクトによる中国コミュニティとの連携をどういうものにするか。

## 確認すること

- 韓冬さん個人としての行動なのか・コミュニティがあるのか
  - それによって、向こうに負担してもらうしごとの大きさが変わる
- 配信に YouTube や Zoom などを使う可能性があるが、金盾に何がブロックされているのか

</details>

**Comment by igrep** [comment]
To: @kakkun61 etc.

2点あります。

(1) いつまでに決めましょうか。
(2) 参考になりそうなリンクとして前回の記録を挙げておきます。

- 反省スレ: https://github.com/haskell-jp/community/issues/17
    - まとめ直したもの: https://docs.google.com/document/d/1viNvVjtMxUYCzCTSK-vo7f7YwtyXI6Y3SF9AYEOitH0/edit
        - P.S. 改めて見るとよくまとまっていてありがたや。
- 取り組んだissue: https://github.com/haskell-jp/community/issues?q=is%3Aissue+is%3Aclosed+label%3AHaskell-Day-2019

スポンサー付けての懇親会は楽しかったけどやっぱいろいろめんどくさかったことが窺われるね... 良くも悪くもどの道オンラインじゃ気にする必要がない 😓

**Comment by kakkun61** [comment]
@igrep レビューありがとう！

期限はそうですね、自分が2月いっぱいはばたばたしてるので2月いっぱいにしましょうかね。

ぜひ関与したい方は **2月いっぱい** にレビューをお願いします。

とりあえず決める項目を洗い出すことが目的なのでお気軽にどうぞお願いします。

**Comment by peacock0803sz** [comment]
主にPyCon JP関連で活動していて、OSSイベントいくつか関わっているので興味ありです :eyes:
一つ言わせていただくと、やり方の前にコンセプトをざっくり決めて(少なくともコアメンバー内では共有)しておいたほうが参加者にもその意図が伝わり、いいイベントになると思っています。

PyCon JP 2020, 2021とスタッフをしているので、(片手間にはなると思いますが)力になれたらと思っています!

**Comment by kakkun61** [comment]
I wrote [a rough plan for Haskell Day Online](https://docs.google.com/document/d/110yycbk0T2IS74nQ84vELEMsXXGgRYdTFM4xSJmY734/).

@winterland1989 I have two questions about the Chinese community.

- Is your suggestion your individual one or the Chinese community's one?
  - It changes what I want you to do.
  - If your individual one, I give you a few tasks. If the community's one, I give it more tasks.
- I am planning to use YouTube. Is YouTube blocked by the 金盾?

**Comment by winterland1989** [comment]
Hi @kakkun61 

It's wonderful to see you get started, today morning I'm discussing with Andrew Boardman(Haskell Foundation people), I think now we have the possibility to host three meetups(China, Japan, and HF) together. I will represent the Chinese community's one.

> I am planning to use YouTube. Is YouTube blocked by the 金盾?

Yes, but I think I can manage to use multiple streaming cast platform, in china I would recommend [bilibili](https://www.bilibili.com/).

**Comment by kakkun61** [comment]
> I think now we have the possibility to host three meetups(China, Japan, and HF) together.

I see. Please let me know, if there are any news about it.

> I will represent the Chinese community's one.

OK 🙆

> Yes, but I think I can manage to use multiple streaming cast platform, in China I would recommend bilibili.

Got it. Thank you.

**Comment by kakkun61** [comment]
I created a Projects board (yet empty). https://github.com/haskell-jp/community/projects/3

**Comment by kakkun61** [comment]
現状の概要です。
A current event plan.

# いつ When

7月 8月ぐらい？
Jul. Aug.?

# 長さ How long

6時間ほど
Approx. 6 hours

各発表15～45分
15-45 minutes / presentation

# 配信方法 Video Delivery

事前録画配信
Pre-recorded video delivery

YouTube のプレミア配信（リアルタイムチャット）
YouTube Premiere (scheduled publication)
Interactive with chat

# 役割としごと Roles and Works

- 発表者 Speaker
  - 発表の録画（母語もしくは英語）
  - Record presentation (mother tongue or English)
  - 字幕作成（日本語・漢語もしくは英語）
  - Subtitle text (Japanese or Chinese or English)
- 編集者 Editor
  - 動画編集 #41
  - Concatenate videos #41
  - 配信サイトへのアップロード
  - Upload the concatenated video
- ほか Others
  - 字幕翻訳 #40
  - Translate subtitles #40
  - ウェブサイト作成 #34
  - Website #34
  - など and so on

**Comment by kakkun61** [comment]
全体方針が決まって、個々のイシューで管理を始めたので、これは閉じる。
