### ISSUE TITLE
テザーサイト作成

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#34]
# ウェブサイト作成

イベント概要など

# 参考

- https://droidkaigi.jp/
- https://rubykaigi.org/
- https://phpcon.php.gr.jp/

**Comment by kakkun61** [comment]
とりあえずテザーサイト

**Comment by kakkun61** [comment]
静的サイト生成しようかと思ったけどベタ書きのペライチでいい気がしてきた。

**Comment by kakkun61** [comment]
https://github.com/haskell-jp/haskell-day-2021-website

**Comment by igrep** [comment]
一つ今日の会議で言い忘れてた。ベタだけど、中国に寄せるつもりで赤をアクセントにするのはいいかも。

**Comment by kakkun61** [comment]
# 2021-05-09 Haskell Day 2021 会議 第2回

[議事録](https://docs.google.com/document/d/1DuQXGE1z_O89S0aCbIZn1LGM3O8sJIe23eXeEYDWBa4/)

今回は中国も含め色んな人に参加してほしいので、人を選びそうな暗い感じではなく広く受け入れられそうな明るい色を基調にする。

最初のテザーサイトは5月23日リリース目標。

最初のテザーサイトに記載すること
- タイトル
- 概要
  - Haskellに関するイベントです
  - オンライン開催であること
  - ~中国と一緒にやること~
  - 発表者を募集形式にすること
  - いつごろ募集開始予定かも記載する
    - 6月初旬予定
  - 場所・時
  - 過去イベントへのリンク
  - Twitter ハッシュタグ
    - タイトルに入れておく

https://github.com/haskell-jp/haskell-jp.github.io に配置する。

**Comment by kakkun61** [comment]
テザーサイトをリリースしたのでクローズする

https://haskell.jp/haskell-day-2021/
