### ISSUE TITLE
Code of Conduct の改訂

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#35]
# Code of Conduct の改訂

- 特にオンラインイベントに合わせて改訂する

https://github.com/haskell-jp/community/blob/master/haskell-day-2019/CODE_OF_CONDUCT.md

**Comment by igrep** [comment]
こちら、個人的には以前Haskell-jp Adminsで翻訳した、Haskell FoundationのGRCをそのまま利用するのがよいのではないかと考えています。多少、イベント特有の具体的な注記を加えた方が良いかも知れませんが。

**Comment by kakkun61** [comment]
GRC は規範というより宣誓という感じですが、代用できると思います

**Comment by igrep** [comment]
と、いうわけでGRCの翻訳をようやくHaskell-jpにも適用する方向で進めています
https://github.com/haskell-jp/community/pull/49

**Comment by kakkun61** [comment]
GRC を適用するのでクローズ
