### ISSUE TITLE
Guidelines For Respectful Communication の翻訳

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#36]
# Guidelines For Respectful Communication の翻訳

- 英語
- 漢語

## 先行

#35

**Comment by igrep** [comment]
https://github.com/haskell-jp/community/pull/49 をマージしました。ブログにもなるべく早くアナウンスを書こうと思います。

**Comment by kakkun61** [comment]
日本国内向けイベントになったので翻訳はやらない [第4回会議](https://docs.google.com/document/d/1wyq91a5dVXGuDHd3rpQuHNIyBio4mq7QU6Fp72cHMf4/)
