### ISSUE TITLE
発表者募集方法

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#39]
# 発表者募集方法

- 何を使って
- 発表者決定方法
- ウェブサイトでの案内
- 募集ブログ

## 先行

#37

**Comment by nakaji-dayo** [comment]
とりあえず、検討されていたことを引用

[Haskell Day 2020 (2021) Online: Plans](https://docs.google.com/document/d/110yycbk0T2IS74nQ84vELEMsXXGgRYdTFM4xSJmY734/edit#heading=h.5305a471ogvu)

# 発表者募集方法
- 運営からオファー
  - Pros:
    - ある程度、発表の質などをコントロールできる
  - Cons:
    - 他に発表したい人がいる可能性、在日もしくは日本語話者の Haskeller はほとんど Haskell-jp 内にいる可能性が高いが
- 公募
  - Pros:
    - Haskell-jp 外の発表希望者も応募できる
    - 公平性がある
    - 公募の選択にも公平性は必要
  - Cons:
    - 質などがコントロールできない、おそらく応募者にそのような人は少ないが

**Comment by nakaji-dayo** [comment]
上記のpros/consは次の軸

- 質
- 公平性

また、次の検討事項がある

- 公募の場合、「公募の選択」の公平性

----

私の意見としては、
- ある程度の質のコントロールは必要だと思う
  - 各発表のクオリティと言うよりかは、初心者向け・上級者向け等全体のバランスとかが懸念
- 公平性もあると良いが、多くの参加者は関心ないと思う
- 公募の選択の公平性を示すなら、「投票で決定」が妥当だと思う

よって、以下を提案する
- オファー枠と公募枠(選択は投票)を用意
  - 上記のメリット。一方応募・投票受付など運営コスト掛かる。
- 公募のみだが、選択に運営枠と投票枠を用意
- ちょっとクローズドな公募
  - 前回と同じ
  - 公平性が低いが、多分運営的に楽なはず

**Comment by nakaji-dayo** [comment]
募集+発表者決定方法についても、中国側について分けた議論が必要だと思う

「運営からのオファー」が有力なのは、Haskell-jpのコミュニティの状態に依存している。
中国側の状況はわからないので、中国側の運営に意見伺う必要があるかも。
（何も情報なくてこちらが決めるなら、「公募」にせざる得ないと思った）

----

# 進捗

## 何を使って

https://haskell-jp.slack.com/archives/CAXQ09PN2/p1620189035017400
@igrep さんの調査から、microsoft 365のFormで良さそう。

## 発表者決定方法

- 5/9 mtgで話して決める
  - 上記の選択内、または別の方法がないか議論
 
  

## ウェブサイトでの案内

- 5/9 mtgで担当決める
  - 要項は作られている所
  - フォーム
- 「発表者決定方法」に基づいて作成

#### 応募要件
  - 入力内容
    - タイトル
      - 借りとかでも良いはず
    -   概要
    - 対象者
    - 発表時間
    - チェック: 行動規範を遵守します。動画の公開に同意、注意事項をよく読んだ的な
  - 要求
    - 当日の参加（時間枠は不明なので、1日空いていること）
    - ちゃんと期限までに提出してね的な


## 募集ブログ

- 5/9 mtgで担当決める

- 何を書く
  - テザーを更新した上で、twitterに書くだけで良いのでは?
  - blogだけ見ている人、いるかな
  - 経緯(中国と共同開催、オンライン)の説明とか

**Comment by nakaji-dayo** [comment]
フォーム一旦作りましたが、無料版だと共同編集できないっぽい

https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__tZgfl9UMVk4TlNCOEFPQVpZVzc1SjlZNEpDUDdTQi4u

**Comment by kakkun61** [comment]
募集の開始 https://github.com/haskell-jp/haskell-jp.github.io/pull/27
