### ISSUE TITLE
HD2019: フレーバー要素

### ISSUE THREAD

**Issue by fumieval** [haskell-jp/community#4]
* テーマとキャッチコピー
* ノベルティ配布
* ロゴ

**Comment by mizunashi-mana** [comment]
テーマとキャッチコピーは，別のイシューにして投票制にしてみるのはどうでしょう？ 投票締め切りの期限も設けたほうがいいと思います．それほどかっちり方式を決める必要はなくて，どっちかというと意見を出してもらう方に専念するのがいいと思います．

念の為「一番得票が高い人のが採用されるわけではなく，最終的には運営人員で話し合って決める」ということは断っておくといいと思いますが．

**Comment by igrep** [comment]
すみません、このIssueのうち「テーマとキャッチコピー」については、今後 https://github.com/haskell-jp/community/issues/5 で話しあいます。
