### ISSUE TITLE
動画編集

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#41]
# 動画編集

- 発表者の作成した動画を結合したり
- 音の大きさをそろえたり

**Comment by kakkun61** [comment]
~YouTube~ Google ブランドアカウントを作成した

https://www.youtube.com/channel/UC3PFuhHhbgWca1UkgvwsTGQ/

**Comment by kakkun61** [comment]
@lotz84 @igrep 試しに権限付与しました

**Comment by kakkun61** [comment]
今はカスタム URL は要件があるのか

> - チャンネル登録者数が 100 人以上であること
> - チャンネルを作成してから 30 日以上経過していること
> - プロフィール写真がアップロードされていること
> - バナー画像がアップロードされていること
> 
> https://support.google.com/youtube/answer/6180214

**Comment by kakkun61** [comment]
動画提出先は @igrep さんの Dropbox を使用する

**Comment by kakkun61** [comment]
休憩中はタイムテーブルを表示

**Comment by kakkun61** [comment]
YouTube 関連は #63 に分離

**Comment by igrep** [comment]
@lotz84 さんがあらかた終えたのでclose
