### ISSUE TITLE
タイトル・テーマを決める

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#43]
@kakkun61 確認のためにissueにします。
https://github.com/haskell-jp/community/issues/30 では「Haskell Day 2020 代替イベント」と銘打ちましたが、ラベルは「Haskell Day 2021」という名前になっています。
これは正式に「Haskell Day 2021」と呼ぶという方針にしたということで良いでしょうか？あるいはこれから決める？
なお、個人的にも「Haskell Day 2021」に賛成です。

**Comment by kakkun61** [comment]
深く考えずにラベル決めましたね……！

2021年に行うイベントとしてユニークなら Haskell Day 2021 がいいと思いました

**Comment by kakkun61** [comment]
このイシューを名前決めイシューにしますかね

**Comment by igrep** [comment]
強いて別案を挙げるなら、Haskell-jpのイベントであることをわかりやすくするために「Haskell **-jp** Day 2021」とつけるのはどうかなぁと実はずっと前から考えてしました 😏 
ただ今回は、中国のコミュニティーも関わる関係上もう一ひねり必要だとは思いますが。

**Comment by peacock0803sz** [comment]
中国語圏も混ざるならAPACはどうでしょう? PyCon界隈はこれ使っています。参考までに...(広げ過ぎかな)

**Comment by kakkun61** [comment]
シンプルに「Haskell Day 2021」でいいんじゃないかなという気がします

**Comment by kakkun61** [comment]
テーマ「Stay Home and Hack Haskell」
Hack *in* Haskell?

**Comment by igrep** [comment]
> シンプルに「Haskell Day 2021」でいいんじゃないかなという気がします

そうやね。敢えて今回変える必要はないか。

> テーマ「Stay Home and Hack Haskell」
Hack _in_ Haskell?

Hack in Haskell でしょうねー。Haskellそのものをハックするって何、Hack GHCならまだ（GHC開発者という意味で）分かるんですけど

**Comment by kakkun61** [comment]
# 2021-05-09 Haskell Day 2021 会議 第2回

[議事録](https://docs.google.com/document/d/1DuQXGE1z_O89S0aCbIZn1LGM3O8sJIe23eXeEYDWBa4/)

「Haskell Day 2021」にする。

テーマはなし。
