### ISSUE TITLE
翻訳したGRCを公開して、Haskell-jp全体の規則として適用する

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#44]
以前翻訳していただいた https://github.com/haskell-jp-admins/GRC-draft をみなさんに承認いただいた上で、こちらのリポジトリーで公開し、Haskell-jp全体のGRCとしたい思います。そして、問題なければHaskell Day 2021でもほぼそのまま利用したいです。

@nobsun 改めて見直して、まだ修正したいところがあれば修正してください 🙇 

関連issue
https://github.com/haskell-jp/community/issues/35 https://github.com/haskell-jp/community/pull/29

**Comment by igrep** [comment]
@nobsun ping.

**Comment by nobsun** [comment]
私としては、特に修正したところはありません。
