### ISSUE TITLE
募集演讲者 （発表者の募集）

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#46]
@winterland1989
现在我们打算在Google Form上公开招募演讲者 。
为了招募演讲者从中国，我们能使用Google Form吗？还是需要其他手段吗？

**Comment by winterland1989** [comment]
可以，这里的VPN很方便

**Comment by igrep** [comment]
谢谢你告诉我。我重新参考了一些网页关于中国的VPN，还是想用Microsoft Forms代替Google Forms。
从中国能没有VPN使用Microsoft Forms吗？

**Comment by winterland1989** [comment]
可以，在中国使用Microsoft Forms会比较方便，不需要VPN，另外我们计划再下个月开展国内的 Haskell 聚会，可否和你们一起，届时我们两边的会场可以同步直播。

**Comment by igrep** [comment]
你是说我们下个月与你的聚会一起举办Haskell Day 2021吗？
很遗憾，我们的准备赶不上下个月。 😞

**Comment by winterland1989** [comment]
你们大概在什么时间 我们可以调整

**Comment by igrep** [comment]
现在Haskell Day 2021预定十一月。

**Comment by igrep** [comment]
你们的聚会是什么样的？演讲者和演讲内容定了？

**Comment by igrep** [comment]
因为 https://github.com/haskell-jp/community/issues/50 的方案(1), 由于我们决定除了嘉宾演讲者的你只在日本征集演讲者，我将结束问题。如果想共同举办的话，请再告诉我们。
