### ISSUE TITLE
テーマとキャッチコピー

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#5]
これまでにSlackで挙がった案（括弧内はコメント）:

- さらなるHaskellの実践に向けて（ちょっとカタい？）
- 趣味Haskell報告も仕事Haskell報告も（「仕事Haskell報告」という言葉を私がHaskell-jpもくもく会中によく使うので）
- さらなる進化に向けて (来年は Version 1.0 から 30 周年記念ですね :wink: )
- 象牙の塔 門破り 橋渡し 条約

**Comment by igrep** [comment]
これいうの忘れてた。個人的に一番気に入ってるのに
- Beyond Functional Programming （PHPCon のbeyondが印象に残ったので）

**Comment by fumieval** [comment]
見た感じ、「さらなる」のような、超えるニュアンスはマストっぽいですね

**Comment by lotz84** [comment]
文脈が分かって無くてすみません。
テーマとキャッチコピーって HaskellDay 2019 のでしたっけ？
それともHaskell-jp 2019年のテーマでしょうか？

**Comment by igrep** [comment]
@lotz84 Haskell Day 2019です。すみません、今ラベルを付けました。

**Comment by lotz84** [comment]
ありがとうございます！ Haskell Day 2019 のテーマですね。

去年でいうと

> Haskellちょっと興味あるからちょっとできるまで

みたいなフレーズですね！

今年も "知らない人でも楽しめる" を意識するなら

* 令和こそHaskellをはじめよう！

"Haskellを好きな人が楽しめる" を意識するなら

* Haskellについて一年で一番熱く語り合える日

などはいかがでしょう 😀

**Comment by fumieval** [comment]
「その日、関数型プログラミングの壁が破られる」

**Comment by igrep** [comment]
アンケート案を作る前に、「Beyond Functional Programming」についてその思いを（わかる人には言わなくてもわかりそうだけど）。
イベントページにも書く予定です。

Haskellは「関数型プログラミング言語」とは呼ばれますが、Haskellの良さは「関数型プログラミング」だけでは語り尽くせません。
そんな、「関数型プログラミング」に必ずしもとらわれないHaskellの魅力を、様々な面から伝える会にしましょう！

**Comment by igrep** [comment]
@fumieval 「象牙の塔 門破り 橋渡し 条約」というのはどういう意味なんですかね？ちょっと申し訳なくもぱっと見でわからず。。。

**Comment by igrep** [comment]
Slackでアンケート案を共有しました。

**Comment by igrep** [comment]
「Beyond Functional Programming」に決定。
イベントページにも反映済み。 https://techplay.jp/event/727059
