### ISSUE TITLE
Haskell Day 2021召开计划的重新考虑（開催計画の再考）

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#50]
@winterland1989

根据[这边的问题](https://github.com/haskell-jp/community/issues/48 )和 @kakkun61 等的议论，我们认为还是做一些简化的Haskell Day 2021比较好。因为除了韩冬先生以外没有人帮忙，所以我担心能不能创建字幕和翻译等等需要时间的任务。

于是，我们准备了两个方案：

- (1) 最低限度计划：
    - 邀请韩冬先生作为嘉宾演讲者。
    - 找其他演讲者在日本。
    - 担心事项：因为中国的演讲者只有韩冬先生，即使同时发布到Bilibili上看的人也很少吧？
- (2) 原计划：
    - 在日本和中国分别招募或邀请演讲者
    - 担心事项：在募集发表者、制作演讲的字幕等各种各样的场面翻译中文和日语，太辛苦。

你选择哪一个？

**Comment by igrep** [comment]
如果韩冬先生没有强烈坚持，我们想尽量选择计划(1)。

**Comment by winterland1989** [comment]
目前看来 方案1比较可行

**Comment by igrep** [comment]
谢谢！我们决定采用方案(1)了。
