### ISSUE TITLE
開催日を決める

### ISSUE THREAD

**Issue by kakkun61** [haskell-jp/community#52]
Haskell Day 2021 の開催日を決める

- Go Conference 2021/11/13
- RubyKaigi 2021/09/09-13
- (2020) JJUG 2020/11/07
- (2020) AWS re:Invent 2020/11/30-12/4

候補日

- 第一候補 11/7
  - 日付が確定してるGo conferenceとはかぶらないように
- 第二候補 11/14

**Comment by igrep** [comment]
https://github.com/haskell-jp/community/issues/51 のとおり、韩冬さんも11/7で 🆗 だそうです！

**Comment by kakkun61** [comment]
7日で
