### ISSUE TITLE
请求你的演讲视频

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#57]
@winterland1989 Haskell Day 2021在YouTube上播放**录制的**视频。各位演讲者提交录制的演讲，我们结合。

我们想请韩冬**用英语**演讲。这是到公开为止的日程。

- 8月6号之前：告诉我们演讲的你的题目和概要，演讲时间。
    - 最好在大约 300 个字符以内的概要。
    - 演讲时间选择一个从约15分钟，约30分钟，约45分钟（除了答疑时间）。
- 9月26号之前：提交你的视频。
- 11月7号：我们播放编辑后结合的视频。
    - 回答问题在YouTube的聊天。
- **11月7号以后：公开结合前的视频。**

如果有在意的事情随时告诉我！

**Comment by winterland1989** [comment]
好的，我会按照日程整理材料，感谢

**Comment by igrep** [comment]
@winterland1989 

> 8月6号之前：告诉我们演讲的你的题目和概要，演讲时间。 

截止日过了。你决定了你的演讲的标题吗？

**Comment by winterland1989** [comment]
这是我计划的主题和概要，您看是否合适

topic：《introduction to Z.Haskell》
abstract: In the past few years, I've been working on a new engineering toolkit to make writing Haskell applications especially network applications easier, that effort became the Z.Haskell project. It includes new array and slice types build on `ByteArray#` provided by GHC runtime, UTF8 based text, and a new IO subsystem based on the libuv, In this talk, I will present many details on how do we solve concrete problems in Z.Haskell, and the project's future plan.

**Comment by igrep** [comment]
@winterland1989 太棒了! 谢谢! 我稍后会更新时间表。
演讲时间45分钟可以吗？

**Comment by winterland1989** [comment]
可以的，我需要在什么时间之前准备好视频？

**Comment by igrep** [comment]
> 9月26号之前：提交你的视频。

**Comment by igrep** [comment]
@winterland1989 进展怎么样？

**Comment by winterland1989** [comment]
> @winterland1989 进展怎么样？

I will send you my video before Friday.

**Comment by igrep** [comment]
@winterland1989 星期五过了。你了手了做视频吗？

**Comment by winterland1989** [comment]
Sorry for the delay, I've met some problem with my network, can you get my video from links below:

https://meeting.tencent.com/v2/cloud-record/share?id=87bcc36a-3579-4d90-b24a-09e12cef78a5&from=3

**Comment by igrep** [comment]
Thank you very much! We'll check in details later. Can you put the original video file on our shared folder on my Dropbox account if you still have it? I'll send the folder's URL soon via Slack DM.

**Comment by igrep** [comment]
NOTE: It seems that I can't download your video from the Tencent page because I can't sign up to the service from Japan. 😞

**Comment by winterland1989** [comment]
I have sent the video file via email to igrep@n.email.ne.jp, if you use another email address please tell me.

**Comment by igrep** [comment]
Thank you for sending! I'll close this issue after checking it.

**Comment by igrep** [comment]
Confirmed! Nice introduction to Z.Haskell!
