### ISSUE TITLE
遵守GRC

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#58]
@winterland1989 在请求演讲之前，为了慎重有一件事要告诉。

我们日前制定了[GRC](https://github.com/haskell-jp/community/blob/master/GRC.md)。这是翻译[Haskell Foundation的GRC](https://haskell.foundation/guidelines-for-respectful-communication/)成日语，后变更运用的主体成Haskell-jp，咨询窗口成Haskell-jp Admins（我和 @kakkun61 ，@lotz84，@nakaji-dayo 等是它的成员）。所以宗旨不变。演讲时请务必遵守，而且如果有什么问题的话，请和我们商量。

※中国語が分からないメンバーにメンションしているので和訳も載せておきます。

発表を依頼する前に一つ念のためお伝えすべきことがありました。我々は先日GRCを制定しました。こちらはHaskell FoundationのGRCを和訳したもので、運用の主体をHaskell-jpに、相談窓口をHaskell-jp Admins（私や @kakkun61 ，@lotz84，@nakaji-dayo などがそのメンバーです）に変更したものです。なので趣旨は変わりません。発表するにあたって必ず守っていただき、また何かトラブルがあれば、我々にご相談ください。

**Comment by winterland1989** [comment]
好的，没有问题
