### ISSUE TITLE
YouTube 動画の概要など、公開時の設定

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#65]
- [ ] 動画の概要
- [ ] プレミア公開のカウントダウン
    - [x] 何分前から公開すればいい？
        - オープニングにカウントダウンを含めよう
    - [ ] カウントダウンのテーマ（担当の好みで！）
- [ ] 投稿者もチャットにURLを投稿できるようにしたい https://github.com/haskell-jp/community/issues/63#issuecomment-932683462

**Comment by kakkun61** [comment]
- 詳細
  - タイトル
    - Haskell Day 2021
  - 説明
    - Haskell Day は初心者から上級者の方まで沢山の人に楽しんでいただけるようなプログラミング言語 Haskell に関する発表が行われる国内最大級のイベントです。
    - 前回まではオンサイトで100人規模で開催していましたが、今年は新型コロナウイルス（SARS-CoV-2）による影響を考慮し、オンラインでの開催となります。
  - サムネイル
    - エンディングのロゴがいいかな
  - 再生リスト
    - なし
  - 視聴者
    - いいえ、子ども向けではありません
  - 有料プロモーション
    - いいえ
  - チャプターの自動生成
    - はい
    - あとで手動修正
  - タグ
    - Haskell
    - Programming
    - プログラミング
  - 言語とキャプション
    - 日本語
    - 米国内のテレビ……ありません
  - 撮影日と場所
    - なし
    - なし
  - ライセンス
    - 標準
    - 埋め込み
      - 許可
    - フィード
      - はい
  - ショート動画
    - 許可
  - カテゴリ
    - 科学と技術
  - コメントと評価
    - 不適切な可能性があるコメントを保留して確認する
      - 人気順
    - この動画を高く評価または低く評価した視聴者の数を表示する
      - はい
- 動画の要素
  - 字幕を追加
    - なし
  - 終了画面の追加
    - なし
  - カードの追加
    - なし
- 公開設定
  - 公開設定
    - スケジュールを設定
      - 2021/11/07 13:00 東京
      - プレミア公開
        - はい
  - カウントダウンテーマ
    - 従来
    - 2分
