### ISSUE TITLE
山本悠滋の発表時間

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#69]
※編集時に意識しないといけないので、 @lotz84 さんもassignしました。

今更気づいたんですが、私の発表について「元々の時間だとハイペースすぎるので再生速度を0.8倍くらいにしたい」という要件を新しいタイムテーブルに反映し忘れてしまったようです。

https://haskell.jp/haskell-day-2021/

> 15:30～15:45 | slack-log の紹介

仮に元々の速度で再生するにしても、ほぼ15分ぴったりで終わるわけですから次の発表までの余裕がなさ過ぎるでしょう。
なので5分延ばして

15:30～15:50 | slack-log の紹介

に変えたいです。

**Comment by kakkun61** [comment]
発表時間が

15分 / 0.8 = 18.75分

で 18分45秒になって

その後の休憩が 6分15秒

それ以降（GHCによるHaskellプログラムの動かし方・クロージング）が後ろに5分ずれる という認識で合ってますか？

（まあ 15秒はちゃんとしなくてもいいと思うけど）

**Comment by igrep** [comment]
となると 15:50 終了ではなく

15:30～15:55 | slack-log の紹介

ですね。何倍速にするか決めかねているところだったのでとりあえず15:50までと思ってましたが、確かにその方がどの道いいかぁ

**Comment by igrep** [comment]
申し訳ない、表に書かれた時間からは休憩時間が抜けているのね...
だからご認識のとおりこう 👇 か。

15:30～15:50 | slack-log の紹介
15:55～16:20 | GHC による Haskell プログラムの動かし方
16:20～16:25 | クロージング

**Comment by igrep** [comment]
ウェブサイトは更新しておきました！ @lotz84 あとは頼んだ！
