### ISSUE TITLE
懇親会の飲食物: 予算が許せばもう少し充実させたい

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#7]
@fumieval くんがSlackでいろいろ上げてくれたので、ひとまず先に必要になりそうな額を見積もっていただきたいです！

~~ちなみに去年は10万円を少し下回る程度かかっています。~~
追記: すみません、実際に確認したらもっと低予算でした。

# 去年の内訳 （IIJ広報からいただいたメールより抜粋）:

> ■宅配ピザ　60,000円（税込）
ピザハット神田店（請求書支払い）
■ソフトドリンク3ケース　7,253円（税込）
カクヤス（仮払で対応）
■お菓子類　2,998円（税込）
Amazon（個人購入→立替清算）
その他、広報部の在庫になっている缶ビール類 74本を放出します。

**Comment by fumieval** [comment]
https://docs.google.com/spreadsheets/d/1blboslgMufMc96OE9GBfNNymxj2DvbSiv395T9GFuMg/edit?usp=sharing 飲み物と菓子などをいくつか見繕いました。ワイン、焼酎、チューハイなどに関しては詳しくないため入れませんでしたが、もしおすすめがあれば何なりと

**Comment by igrep** [comment]
メモ: 参考リンク

- [ビアバッシュの段取り - 未来のいつか/hyoshiokの日記](http://hyoshiok.hatenablog.com/entry/20081017/p1)
- http://beer-party.candycane.jp/?utf8=%E2%9C%93&q=110&b=domino&commit=Calculate

**Comment by fumieval** [comment]
内訳確認しました。飲み物だけで50000円を越すのはさすがに贅沢すぎたか…？

**Comment by igrep** [comment]
確かに。とはいえ、とりあえずIIJ以外のスポンサーやカンパも募ってみて、その集まり具合を見てから判断でもよいかと。（内訳について、通知を送ってなくて済みません。コメントを追記するべきでした。 🙇

**Comment by igrep** [comment]
Slackより: ピザが不評だったことを受け、ケータリングを注文することを検討中。
候補:

- https://ケータリング東京ナビ.com/
- https://deli-cate.com/

https://haskell-jp.slack.com/archives/CAXQ09PN2/p1560150087007400?thread_ts=1560145966.007300&cid=CAXQ09PN2

**Comment by igrep** [comment]
現在の欲しい予算（~~しまったこの予算消費税8%で計算してるぞ...~~ 飲み物代もお酒が多いでしょうし消費税10%で概算しました。軽減税率が適用されたりしないかな～）

合計: 344,092円

- 飲み物代: 65,792円（上記のスプレッドシートより。消費税をすべて10%と仮定して概算し直した）
- ケータリング（[こちらのSlackのスレッドより](https://haskell-jp.slack.com/archives/CAXQ09PN2/p1560145966007300)。高額な方）: 2300 * 110 * 1.1 = 278,300円

**Comment by igrep** [comment]
@fumieval くんと口頭で話し合ったメモ

- お金は原則fumiくんの口座に振り込んでもらう
    - IIJからのお金は当日手渡し
- 注文もfumiくんにお願いする
- 当日持って行けるものに限りがあるので、fumiくんが持って行ける範囲内で飲み物を絞る
    - fumiくんが当日持ってくる分以外はカクヤスで賄うか、
    - Amazonから当日会場宛てに送ってもらう

**Comment by igrep** [comment]
⚠️ 注意 ⚠️ 
現状参加人数が想定より大分少ないので、もっと少なくていいかも。
速くタイムテーブルを決めて繰り返し宣伝し、当日の人数を再度見積もる

**Comment by igrep** [comment]
私のTODO: お茶やコーヒーを振る舞いたいそうなのでお湯が沸かせるかTECH PLAYに相談する

**Comment by igrep** [comment]
懇親会関係での残りのTODOは #12 や #13 で。
