### ISSUE TITLE
開催終了後、イベントページなどの修正

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#72]
- [x] 終了したという旨をどこかに書く
- [x] 各発表の資料のURLを公開
- [x] Advent Calendarの募集ツイートを行い、固定する

**Comment by igrep** [comment]
https://twitter.com/haskell_jp/status/1457257859339603971 固定ツイートできた

**Comment by nakaji-dayo** [comment]
終了したことを記載
各発表に動画・資料のURL記載
https://haskell.jp/haskell-day-2021/#
