### ISSUE TITLE
資金調達

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#8]
IIJはじめ各社にスポンサーを依頼します。
それでも足りなければカンパや寄付枠を募る方向で。

**Comment by igrep** [comment]
@kakkun61 IIJの広報とのやりとりをお願いしたいです。
手始めに今年度後期の予算の状況や、スポンサーの条件などを聞いてみてください（恐らく去年と同じ感じになるとは思いますが

**Comment by igrep** [comment]
✍️ 私のTODO: テーマが決まってイベントページもできたら、スポンサーの募集・依頼を開始する（イベントページに書くのがいいんでしょうね。

**Comment by kakkun61** [comment]
問い合わせメール done

**Comment by kakkun61** [comment]
IIJ からは上限5万円でスポンサーしていただけるとのことです。

**Comment by fumieval** [comment]
じゃあ私は7万円支援します

**Comment by igrep** [comment]
マーベリック株式会社様から「10万円程度」のご提供をいただけるとのことです！
https://haskell-jp.slack.com/archives/CAXQ09PN2/p1560247653007300

**Comment by igrep** [comment]
メモ: TODO: 資金の集め方を検討する。口座振替として別途作る？

**Comment by igrep** [comment]
集め方についての議論はもう終わったと言うことでclose。続きは #12 で。
