### ISSUE TITLE
発表者・テーマ募集

### ISSUE THREAD

**Issue by igrep** [haskell-jp/community#9]
https://github.com/haskell-jp/community/issues/11 で検討した叩き台のスケジュールを参考にする限り、30分のセッションが多くて10個ぐらいまでになりそう。

**Comment by igrep** [comment]
Slackで依頼したみなさんに、このスレッドで発表タイトル（案）をご報告いただくことにしました。

**Comment by igrep** [comment]
これまでに発表の依頼をしたみなさま・ https://haskell-jp.slack.com/archives/CAXQ09PN2/p1558401972080800 で手を挙げていただいたみなさま

そろそろ発表内容について、ぼんやりご検討いただきたく！
https://github.com/haskell-jp/community/issues/9 に、
- 発表タイトル（仮で :ok: ）
- イベントページで掲載する名前
- （できれば）発表の対象者・レベル・前提知識

をコメントしていただきたく！
※ 「やっぱ無理！」と :spoon: を投げるなら今です。

追記: 書き忘れてた。レベル感については、 https://qiita.com/lotz/items/0d68c8440d1f362d0c32 を参考にどうぞ。

**Comment by konn** [comment]
タイトルに関しては今後内容に応じて適宜修正される可能性がありますが、以下の要領でお願い致します。

* 仮タイトル：大規模数値計算を支える Haskell ── Pragmatic Haskell in Large-Scale Numerical Computation
* 名義：石井大海（DeepFlow株式会社）
* 発表の対象者・レベル： 全体の概要は初中級程度の知識があれば、細部に関してはある程度Haskell による開発経験があれば理解可能なようになる予定です。

他に発表概要などが必要になったりする予定はありますでしょうか？

**Comment by igrep** [comment]
ありがとうございます！

> 他に発表概要などが必要になったりする予定はありますでしょうか？

特にパンフレットの作成などは計画してないので、不要です。 👍

**Comment by nobsun** [comment]
- 発表*仮*タイトル： 関数型(function type)を見つめるプログラミング
- 発表者名：山下伸夫（聖徳大学）
- 発表者の対象者：初級，リスト内包表記，ツリー構造がなんとなく解る

でお願いします．

**Comment by matsubara0507** [comment]
- 発表タイトル: Haskell で作る競技型イベントの裏側
- イベントページで掲載する名前: 松原信忠
- 発表の対象者・レベル: 
    - NOVICE 半分 COMPETENT 半分ぐらい？
    - Haskell 自体というよりは Haskell で作ったシステムの紹介
    - ただそのシステムは extensible とか rio とか stm とかアドバンスドなパッケージを多用してる

**Comment by lotz84** [comment]
* 発表タイトル：関数と型で理解する自動微分
* 発表者名：lotz
* 発表者の対象者：Advanced Beginner + Optics がちょっとわかると良いかも

でお願いします！

**Comment by egisatoshi** [comment]
EgisonのパターンマッチのTemplate Haskellによる実装が最近完成したので，このライブラリの使い方と実装について発表したいと考えています．
まだ枠ありますでしょうか？
(4ヶ月前は完成するかまだわからなかったので手を挙げれませんでした...)

https://github.com/egison/egison-haskell

同様の機能をSchemeのマクロとして実装したライブラリについては，今年のScheme Workshopで発表した実績があります．

https://github.com/egison/egison-scheme

よろしくお願い致します．

**Comment by igrep** [comment]
@egisatoshi すばらしい！ちょうど昨日一枠キャンセルの連絡があったので、ぜひお願いしたいです！
今回も大まかにレベルごとに時間帯を分けたいので、前提知識などを教えていただけないでしょうか？

**Comment by igrep** [comment]
@egisatoshi 続けて済みません。もう何点か。

1. あと、このisssueの冒頭にも書いてますが原則発表時間は **質問時間を含めて30分** としますのでご了承ください。
1. https://github.com/haskell-jp/community/issues/9#issuecomment-529318927 のとおり、下記を教えてください。
    - 発表のタイトル（仮で 🆗 ）
    - イベントページで掲載する名前

**Comment by egisatoshi** [comment]
@igrep ありがとうございます！今日中にフォーマット埋めてお送りします．

**Comment by egisatoshi** [comment]
@igrep 
今回紹介したいHaskellライブラリを実装したチームメンバーの @kotapiku が発表する予定です．

仮タイトル：HaskellメタプログラミングによるEgisonのパターンマッチの実装
名義：kotapiku ( @kotapiku )
発表の対象者・レベル： 紹介するライブラリの使いかたの解説は初心者を対象に含みます。実装の解説は型レベルプログラミングを含むため上級者向けになる予定です。

よろしくおねがいします．

**Comment by egisatoshi** [comment]
@igrep 
すみません．今回の発表やはり，私がします．
発表の内容について以下のように更新させてください．

仮タイトル：HaskellメタプログラミングによるEgisonのパターンマッチの実装
名義：江木聡志 (楽天技術研究所)
発表の対象者・レベル： 紹介するライブラリの使いかたの解説は初心者を対象に含みます。実装の解説は型レベルプログラミングを含むため上級者向けになる予定です。

よろしくおねがいします．

**Comment by fumieval** [comment]
* 発表タイトル HKD(Higher Kinded Datatype)
* イベントページで掲載する名前 fumieval
* 発表の対象者・レベル・前提知識 Haskellのレコード

**Comment by y-taka-23** [comment]
* 仮タイトル : GHCJS による Web フロントエンド開発
* 名義 : チェシャ猫
* 発表の対象者 : Advanced Beginner

よろしくお願いします。

**Comment by aiya000** [comment]
- 仮発表タイトル: GHC・阿鼻叫喚のDerivingストラテジー
- イベントページで掲載する名前: aiya000
- 発表の対象者・レベル・前提知識:
    - Advanced beginner
    - ちょっとしたスクリプトを書ける程度の、Haskellの理解を持つ人
        - GHC拡張の理解がなくても大丈夫
        - しっかりしたアプリケーションを書けなくても大丈夫

DerivingStrategies拡張の持つ各機能を、GeneralizedNewtypeDerivingとDerivingViaを中心にまとめる発表です :sunny: 
よろしくおねがいします！
